version: "3.2"

services:
  traefik:
    image: traefik:1.7-alpine
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=example.com"
      - "--acme=false"
      - "--acme.acmelogging=true"
      - "--acme.email=webmaster@example.com"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "./acme.json:/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always

  syspass:
    image: crazymax/syspass:latest
    container_name: syspass
    volumes:
      - "./data:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=syspass"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:syspass.example.com"
    environment:
      - "TZ=Europe/Paris"
    restart: always
